AUTOCOMPLETE_FIELDS = ['product_name', 'brands', 'categories']
INDEX_ALIAS = 'openfoodfacts'
INDEX_ALIAS_PATTERN = INDEX_ALIAS + "-*"
MAX_RESULTS = 100

UNDOCUMENTED_FIELDS = [
    'countries_en',
    'pnns_groups_1',
    'pnns_groups_2',
    'states',
    'states_tags',
    'states_en',
    'ecoscore_grade',
    'image_nutrition_url',
    'image_nutrition_small_url',
    'origins_en',
    'ingredients_tags',
    'image_ingredients_url',
    'image_ingredients_small_url',
    'salt_100g',
    'fruits_vegetables_nuts_estimate_100g',
    'fruits_vegetables_nuts_estimate_from_ingredients_100g',
    'fruits_vegetables_nuts_dried_100g',
    'categories_en',
    'nutriscore_score',
    'nutriscore_grade',
    'food_groups',
    'food_groups_tags',
    'food_groups_en',
    'ecoscore_score',
    'main_category_en',
    'additives_en',
    'nova_group',
    'labels_en',
    'allergens',
    'packaging_en',
    'packaging_text',
    'serving_quantity',
    'carbon_footprint_from_meat_or_fish_100g',
    'energy_from_fat_100g',
    'folates_100g',
    'soluble_fiber_100g',
    'insoluble_fiber_100g',
    'phylloquinone_100g',
    'cocoa_100g',
    'choline_100g',
    'inositol_100g',
    'collagen_meat_protein_ratio_100g',
    'beta_carotene_100g',
    'chlorophyl_100g',
    'glycemic_index_100g',
    'water_hardness_100g',
    'beta_glucan_100g',
    'carnitine_100g',
    'traces_en',
    'brand_owner',
    'abbreviated_product_name',
    'allergens_en',
]